server:
  port: 2333
  address: "0.0.0.0"
  password: "rider"
lavalink:
  server:
    password: "rider"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      spotify: true
    spotify:
      client-id: "12066741cded475099e33c639d00741d"
      client-secret: "8cce0beb94d34f05b169c49dc818e361"
  metrics:
    prometheus:
      enabled: true
  advanced:
    cache:
      enabled: true
      track: true
      rest: true
    constraints:
      enabled: true
      cpu: true
      memory: true
      nope: false
    youtube-search: true
    opus:
      enabled: true
      lavaplayer: true
      ffmpeg: true
  sora:
    enabled: false
  sentry:
    dsn: ""
  player-update-threshold: 10
  event-buffer-size: 10
  item-cache-capacity: 1000
  http:
    port: 2333
    address: "0.0.0.0"
